apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlds.fullname" . }}
  labels:
    {{- include "hlds.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hlds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hlds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hlds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              set -e

              sed -i 's|\"newbie\" \"password\"|\"$(amxmodx_username)\" \"$(amxmodx_password)\"|' /hlds_l/{{ .Values.hlds.game }}/addons/amxmodx/configs/users.ini
              
              /hlds_l/hlds_run -game {{ .Values.hlds.game }} -nomaster -insecure -pingboost 1 +map {{ .Values.hlds.map }} +maxplayers {{ .Values.hlds.maxplayers }} +rcon_password $(rcon_password)
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nc -uz 127.0.0.1 {{ .Values.service.port }}" ]
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nc -uz 127.0.0.1 {{ .Values.service.port }}" ]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: rcon_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "hlds.fullname" . }}
                  key: rcon_password
            - name: amxmodx_username
              valueFrom:
                secretKeyRef:
                  name: {{ include "hlds.fullname" . }}-amxmodx
                  key: amxmodx_username
            - name: amxmodx_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "hlds.fullname" . }}-amxmodx
                  key: amxmodx_password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
