apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlds.fullname" . }}
  labels:
    {{- include "hlds.labels" . | nindent 4 }}
type: Opaque
data:
  rcon_password: {{ .Values.hlds.rcon_password | b64enc | quote }}
