apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlds.fullname" . }}
  labels:
    {{- include "hlds.labels" . | nindent 4 }}
type: Opaque
data:
  rcon_password: {{ .Values.hlds.rcon_password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlds.fullname" . }}-amxmodx
  labels:
    {{- include "hlds.labels" . | nindent 4 }}
type: Opaque
data:
  amxmodx_username: {{ .Values.hlds.amxmodx.username | b64enc | quote }}
  amxmodx_password: {{ .Values.hlds.amxmodx.password | b64enc | quote }}
